# GitLab CI/CD Pipeline Configuration

stages:
  - lint
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

# ============================================
# Lint Stage
# ============================================
lint:eslint:
  stage: lint
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run lint
  only:
    - merge_requests
    - main
    - develop

lint:format:
  stage: lint
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run format:check
  only:
    - merge_requests
    - main
    - develop

# ============================================
# Test Stage
# ============================================
test:
  stage: test
  image: node:${NODE_VERSION}
  services:
    - postgres:15-alpine
    - redis:7-alpine
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    DATABASE_URL: "postgresql://test_user:test_password@postgres:5432/test_db"
    REDIS_URL: "redis://redis:6379"
  script:
    - npm ci
    - npm run test:coverage
  coverage: '/Coverage: \d+\.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - merge_requests
    - main
    - develop

# ============================================
# Build Stage
# ============================================
build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
      - build/
    expire_in: 1 week
  only:
    - main
    - develop
    - tags

# ============================================
# Docker Build Stage
# ============================================
docker-build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
    - develop
    - tags

# ============================================
# Deploy to Staging
# ============================================
deploy:staging:
  stage: deploy
  image: alpine:latest
  environment:
    name: staging
    url: https://staging.example.com
  script:
    - apk add --no-cache curl
    - echo "Deploying to staging..."
    # Add your deployment commands here
  only:
    - develop
  when: manual

# ============================================
# Deploy to Production
# ============================================
deploy:production:
  stage: deploy
  image: alpine:latest
  environment:
    name: production
    url: https://example.com
  script:
    - apk add --no-cache curl
    - echo "Deploying to production..."
    # Add your deployment commands here
  only:
    - main
    - tags
  when: manual

# ============================================
# Security Scan
# ============================================
security:scan:
  stage: test
  image: aquasec/trivy:latest
  script:
    - trivy fs --severity HIGH,CRITICAL --exit-code 1 .
  only:
    - merge_requests
    - main
    - develop

# ============================================
# Dependency Check
# ============================================
dependency-check:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm audit --audit-level=moderate
  allow_failure: true
  only:
    - merge_requests
    - main
    - develop

